kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: jchu
  LINUX_OUTPUT: jchu.linux
  WINDOWS_OUTPUT: jchu.exe


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: $${LINUX_OUTPUT}
          os: linux
        - name: $${WINDOWS_OUTPUT}
          os: windows

  - name: 编译1
    image: ccr.ccs.tencentyun.com/pangum/drone
    commands:
      - ls -al ${LINUX_OUTPUT}
      - ls -al ${WINDOWS_OUTPUT}
      - chmod +x ${LINUX_OUTPUT}
      - ./${LINUX_OUTPUT}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      branch:
        - release/*
    environment:
      VERSION: $${DRONE_BRANCH##release/v}
      TOKEN:
        from_secret: token_github
    settings:
      owner: storezhang
      repo: $${NAME}
      release:
        tag: v$${VERSION}
        token: $${TOKEN}
        assets:
          - label: $${NAME}-$${VERSION}-linux-amd64
            name: Linux可执行程序
            filename: $${LINUX_OUTPUT}
          - label: $${NAME}-$${VERSION}-windows-amd64.exe
            name: Windows可执行程序
            filename: $${WINDOWS_OUTPUT}


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
