kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: jchu
  LINUX_OUTPUT: $${NAME}.linux
  WINDOWS_OUTPUT: $${NAME}.exe


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: $${LINUX_OUTPUT}
          os: linux
        - name: $${WINDOWS_OUTPUT}
          os: windows

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      branch:
        - release/*
    environment:
      TAG: $${DRONE_BRANCH##release/v}
    settings:
      owner: storezhang
      repo: $${NAME}
      release:
        tag: $${DRONE_BRANCH##release/v}
        token:
          from_secret: token_github
        assets:
          - label: $${NAME}-$${TAG}-linux-amd64
            name: Linux可执行程序
            filename: $${LINUX_OUTPUT}
          - label: $${NAME}-$${TAG}-windows-amd64.exe
            name: Windows可执行程序
            filename: $${WINDOWS_OUTPUT}


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
