kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: jchu
  LINUX_OUTPUT: jchu.linux
  WINDOWS_OUTPUT: jchu.exe


trigger:
  tag:
    exclude:
      - tag


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      compress:
        enabled: false
      outputs:
        - name: $${LINUX_OUTPUT}
          os: linux
        - name: $${WINDOWS_OUTPUT}
          os: windows

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      branch:
        - release/*
    environment:
      VERSION: $${DRONE_BRANCH##release/v}
      TOKEN:
        from_secret: token_github
    settings:
      owner: storezhang
      repo: $${NAME}
      release:
        tag: v$${VERSION}
        token: $${TOKEN}
        assets:
          - label: $${NAME}-$${VERSION}-linux-amd64
            name: $${NAME}
            file: $${LINUX_OUTPUT}
          - label: $${NAME}-$${VERSION}-windows-amd64.exe
            name: $${NAME}.exe
            file: $${WINDOWS_OUTPUT}


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
