kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: jchu
  OUTPUT_LINUX: jchu.amd64.lin
  OUTPUT_WINDOWS: jchu.amd64.exe
  OUTPUT_MAC: jchu.amd64.mac
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: $${OUTPUT_LINUX}
          os: linux
          arch: amd64
        - name: $${OUTPUT_WINDOWS}
          os: windows
          arch: amd64
        - name: $${OUTPUT_MAC}
          os: darwin
          arch: amd64

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    when:
      event:
        - tag
    settings:
      output: $${CHANGELOG_TAG_OUTPUT}
      tag: $${DRONE_TAG}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      event:
        - tag
    environment:
      VERSION: $${DRONE_TAG##v}
      TOKEN:
        from_secret: token_github
    settings:
      release:
        tag: v$${VERSION}
        token: $${TOKEN}
        body: exe:file("$${CHANGELOG_TAG_OUTPUT}")
        assets:
          - name: $${NAME}-$${VERSION}-linux-amd64
            file: $${OUTPUT_LINUX}
          - name: $${NAME}-$${VERSION}-windows-amd64.exe
            file: $${OUTPUT_WINDOWS}
          - name: $${NAME}-$${VERSION}-darwin-amd64
            file: $${OUTPUT_MAC}


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
