kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: jchu
  LINUX_OUTPUT: jchu.amd64.lin
  WINDOWS_OUTPUT: jchu.amd64.exe
  MAC_OUTPUT: jchu.amd64.mac


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: $${LINUX_OUTPUT}
          os: linux
          arch: amd64
        - name: $${WINDOWS_OUTPUT}
          os: windows
          arch: amd64
        - name: $${MAC_OUTPUT}
          os: darwin
          arch: amd64

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      event:
        - tag
    environment:
      VERSION: $${DRONE_TAG##v}
      TOKEN:
        from_secret: token_github
    settings:
      release:
        tag: v$${VERSION}
        token: $${TOKEN}
        body: CHANGELOG.md
        assets:
          - name: $${NAME}-$${VERSION}-linux-amd64
            file: $${LINUX_OUTPUT}
          - name: $${NAME}-$${VERSION}-windows-amd64.exe
            file: $${WINDOWS_OUTPUT}
          - name: $${NAME}-$${VERSION}-darwin-amd64
            file: $${MAC_OUTPUT}


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
